name: base
channels:
  - conda-forge
dependencies:
  - python=3.9
  # - pytorch::pytorch
  # - pytorch::torchvision
  # - cudatoolkit=11.3
  # - matplotlib
  # - numpy
  # - pandas
  # - opencv
  # - py-opencv
  # - ipywidgets
  # - scipy
  # - seaborn
  # - scikit-image
  # - scikit-learn
  - pip
  - pip:
    # - albumentations
    # - black
    # - flake8
    # - Pillow
    # - pretrainedmodels
    # - pydicom
    # - pytorch-lightning
    # - torchinfo
    # - tqdm
    # - statsmodels
