name: base
channels:
  - conda-forge
  # - pytorch
dependencies:
  - python=3.8
  # - pytorch=1.9.0
  # - cudatoolkit=11.1
  # - torchvision
  # - matplotlib
  # - numpy
  # - pandas
  # - scipy
  # - seaborn
  # - scikit-image
  # - scikit-learn
  - pip
  - pip:
    # - albumentations
    # - black
    - flake8
    # - opencv-python-headless
    # - Pillow
    # - pretrainedmodels
    # - pydicom
    # - pytorch-lightning
    # - torchsummary
    # - tqdm
    # - statsmodels
