name: base
channels:
  - conda-forge
dependencies:
  #### Do not change Python version here!       ###
  #### If you need Python of different version, ###
  #### specify other base image in Dockerfile   ###
  ####  - <channel>::package=0.0 ####
  # - pytorch::pytorch
  # - pytorch::torchvision
  # - cudatoolkit=11.3
  # - pytorch-lightning
  # - torchinfo
  - albumentations
  - black
  - flake8
  - matplotlib
  - numpy
  - pandas
  - opencv
  - pillow
  - scipy
  - seaborn
  - scikit-image
  - scikit-learn
  - statsmodels
  - tqdm
